language: rust
rust: 1.34.0

matrix:
  allow_failures:
  - os: windows
  include:
  - os: linux
  - os: linux
    env:
    - FEATURES: "--features=static"
  - os: osx
  - os: osx
    env:
    - FEATURES: "--features=static"
  - os: osx
    osx_image: xcode8.0 # macOS 10.11 "El Capitan"
  - os: osx
    osx_image: xcode8.0 # macOS 10.11 "El Capitan"
    env:
    - FEATURES: "--features=static"
  - os: windows
    env:
    - ROSY_RUBY: ruby
    - ROSY_RUBY_VERSION: "$RUBY_VERSION"
  - os: windows
    env:
    - ROSY_RUBY: ruby
    - ROSY_RUBY_VERSION: "$RUBY_VERSION"
    - FEATURES: "--features=static"

env:
  global:
  - RUSTFLAGS: "-Dwarnings"
  - RUST_BACKTRACE: "full"
  - ROSY_RUBY: rvm
  matrix:
  - ROSY_RUBY_VERSION: 2.6.3
  - ROSY_RUBY_VERSION: 2.5.5
  - ROSY_RUBY_VERSION: 2.4.6

cache:
  directories:
  - $HOME/.cargo
  - $HOME/.rvm

install:
- ./scripts/travis/install_ruby.sh
before_script:
- cargo -Vv
- rustc -Vv
- ./scripts/travis/print_ruby_config.sh
script:
- cargo test --no-default-features "$FEATURES"
