language: rust
rust: 1.34.0

matrix:
  allow_failures:
  - os: windows
  include:
  - os: linux
  - os: osx
    osx_image: xcode10.0 # OS X 10.13 High Sierra
  - os: osx
    osx_image: xcode9.0 # OS X 10.12 Sierra
  - os: osx
    osx_image: xcode8.0 # OS X 10.11 El Capitan
  - os: osx
    osx_image: xcode6.4 # OS X 10.10 Yosemite
  - os: windows

env:
  global:
  - RUSTFLAGS: "-Dwarnings"
  - RUST_BACKTRACE: "full"

cache:
  directories:
  - $HOME/.cargo

before_script:
- cargo -Vv
- rustc -Vv
- ruby --version
script:
- cargo test --no-default-features
