language: rust
rust: 1.34.0

os:
- linux
- osx

matrix:
  allow_failures:
  - os: windows
  include:
  - os: linux
    rust: nightly
    env:
    - ROSY_RUBY_VERSION="2.6.3" FEATURES="ruby_2_6,rustc_version"
    script:
    - cargo doc --all --no-deps --no-default-features --features="$FEATURES"
  - os: windows
    env:
    - ROSY_RUBY: ruby
  - os: windows
    env:
    - ROSY_RUBY: ruby
    - FEATURES: "static"

env:
  global:
  - RUSTFLAGS: "-Dwarnings"
  - RUST_BACKTRACE: "full"
  - ROSY_RUBY: rvm
  matrix:
  - ROSY_RUBY_VERSION="2.6.3" FEATURES="ruby_2_6"
  - ROSY_RUBY_VERSION="2.6.3" FEATURES="ruby_2_6,static"
  - ROSY_RUBY_VERSION="2.5.5"
  - ROSY_RUBY_VERSION="2.5.5" FEATURES="static"
  - ROSY_RUBY_VERSION="2.4.6"
  - ROSY_RUBY_VERSION="2.4.6" FEATURES="static"

cache:
  directories:
  - $HOME/.cargo
  - $HOME/.rvm

install:
- ./scripts/travis/install_ruby.sh
before_script:
- cargo -Vv
- rustc -Vv
- ./scripts/travis/print_ruby_config.sh
script:
- cargo test --no-default-features --features="$FEATURES"
